POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=AIzaSyAnzDjrN7PrftRdQVpDVa0CRHddZ754x5U HTTP/1.1
content-type: application/json

{
    "contents":[
        {
            "parts":[
                {
                    "text": "bagaimana buat ayam goreng kfc"
                }
            ]
        }
    ]
}